version: '3.7'

services:

  campaign_generator_prod:
    container_name: campaign_generator_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - angular.env
    ports:
      - '80:80'
